"""
Vulture whitelist for the Distributed AI Agent League System.
Marks intentionally unused imports and variables as acceptable.
"""

# Pydantic model fields that may appear unused
display_name
contact_endpoint
game_types
strategies
capabilities
agent_version
match_id
round_id
opponent_id
role_in_match
timeout_ms
match_context
accepted
reason
estimated_ready_time
opponent_history
opponent_history_hash
parity_choice
confidence
reasoning
strategy_used
decision_time_ms
player_a_choice
player_b_choice
random_number
winner_id
calculation
round_duration_ms
loser_id
final_score
total_rounds
match_duration_ms
game_results
match_stats
player_a_id
player_b_id
scheduled_time
priority
match_config
tournament_id
standings
last_updated
total_matches
completed_matches
error_code
error_message
error_context
recoverable
suggested_action
agent_status
uptime_seconds
current_matches
performance_stats

# FastAPI and Pydantic internals
model_config
model_dump
model_dump_json
from_json
create_reply
create_error_reply

# Strategy pattern methods
strategy_name
choose_move
update_history

# Agent service methods
initialize
shutdown
handle_invitation
handle_move_request
handle_game_over
handle_registration
handle_match_report

# Ollama integration
OllamaClient
GameContext
PromptBuilder
ResponseParser
build_system_prompt
build_user_prompt
extract_and_validate_json
get_strategic_move

# Exception handling attributes
error_code
agent_id
match_id
strategy_type
endpoint
status_code
timeout_duration
operation
field_name
invalid_value
message_type
protocol_version
model_name
response_data
tournament_id
current_state
requested_state

# Configuration constants from consts/__init__.py
LEAGUE_MANAGER_PORT
REFEREE_PORT
PLAYER_PORTS
LEAGUE_MANAGER_URL
REFEREE_URL
OLLAMA_BASE_URL
DEFAULT_OLLAMA_MODEL
DEFAULT_TIMEOUT
MOVE_TIMEOUT
MATCH_TIMEOUT
REGISTRATION_TIMEOUT
MAX_RETRIES
CIRCUIT_BREAKER_THRESHOLD
CIRCUIT_BREAKER_RESET_TIME
EXPONENTIAL_BACKOFF_BASE
JITTER_RANGE
HTTP_CONNECT_TIMEOUT
HTTP_READ_TIMEOUT
HTTP_TOTAL_TIMEOUT
MAX_CONNECTIONS
MAX_KEEPALIVE
PROTOCOL_VERSION
USER_AGENT_PREFIX
GAME_TYPE
MAX_ROUNDS_PER_MATCH
RANDOM_NUMBER_MIN
RANDOM_NUMBER_MAX
LOG_LEVEL
JSON_LOG_FORMAT
LOG_REQUEST_IDS
REGISTRATION_ENDPOINT
HEALTH_ENDPOINT
MCP_ENDPOINT
AVAILABLE_STRATEGIES
LLM_TEMPERATURE
LLM_MAX_TOKENS
LLM_TIMEOUT
MAX_CONCURRENT_MATCHES
ROUND_ROBIN_SCHEDULING
MATCH_CLEANUP_DELAY

# Enum values
MessageType.REGISTER
MessageType.REGISTER_ACK
MessageType.HEARTBEAT
MessageType.HEALTH_CHECK
MessageType.INVITATION
MessageType.INVITATION_ACK
MessageType.MOVE_CALL
MessageType.MOVE_RESPONSE
MessageType.GAME_OVER
MessageType.MATCH_REPORT
MessageType.SCHEDULE_MATCH
MessageType.SCHEDULE_ACK
MessageType.TOURNAMENT_START
MessageType.TOURNAMENT_END
MessageType.STANDINGS_UPDATE
MessageType.ERROR
MessageType.STATUS_UPDATE

AgentRole.PLAYER
AgentRole.REFEREE
AgentRole.MANAGER

ParityChoice.EVEN
ParityChoice.ODD

AgentStatus.IDLE
AgentStatus.BUSY
AgentStatus.OFFLINE
AgentStatus.ERROR

MatchStatus.SCHEDULED
MatchStatus.IN_PROGRESS
MatchStatus.COMPLETED
MatchStatus.CANCELLED
MatchStatus.ERROR

MatchRole.PLAYER_A
MatchRole.PLAYER_B

ProtocolVersion.V1
ProtocolVersion.V2

# Main function entry points
main

# CLI argument parsing
parser
args

# Test functions
test_ollama_integration

# Dataclass fields
agent_id
display_name
contact_endpoint
strategies
capabilities
registration_time
agent_version
matches_played
matches_won
matches_lost
total_rounds_won
total_rounds_played
status
last_seen
current_match_id
win_rate
round_win_rate
points
player_a_id
player_b_id
scheduled_time
winner_id
final_score
match_duration_ms
completed_time

# Background task variables
background_tasks_running

# HTTP client instances
http_client